development:
  adapter: postgresql
  encoding: unicode
  database: email_app
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: email_app_test
  pool: 5
  username: gschool
  password:
